### PR TITLE
Added Thai localization

### PR DESCRIPTION
**Pull request by rumnat**
Hello,

As discussed with Adyen support (request #636787), we would like to suggest this Thai localization made by professional translators.

Thanks.

### CODE REVIEW

**Comment by joostvandijk** [comment]
Hi @rumnat,

Thanks! We'll merge this in our internal repository, for it to be included with the next release.

Kind regards,

Joost

**Comment by rumnat** [comment]
May I know please when it's supposed to be?

**Comment by joostvandijk** [comment]
I expect it to be next Monday. However, with the most recent release, you can already use the strings in your own project, and the SDK will pick them up automatically.

**Comment by rumnat** [comment]
Can you please also check the android PR as well? No one has replied so far. We need them together
https://github.com/Adyen/adyen-android/pull/63

**Comment by joostvandijk** [comment]
Hey @rumnat,

It appears there's been a miscommunication between us, support and you. As we can't guarantee maintenance of the Thai localization, we prefer not adding it to our project. However, we did add functionality in the latest release to add localization yourself. Simply include these strings in your own bundle, and the SDK will pick them up automatically.

Hope this works for you.

Thanks, and sorry for the inconvenience.

Joost

**Pull request closed without merging**
