### PR TITLE
Exclude armv7 architectures

### LINKED ISSUE #635: [BUG] Failing to archive with Xcode 13 with adyen 3.8.4 version
**Describe the bug**
Try to create archive with Xcode 13 but failing. Error messages being displayed in attached screenshot

**Expected behavior**
Archive should be created

**Screenshots**
Screenshot 2021-09-22 at 4 27 10 pm

**Smartphone (please compl
ete the following information):**
 - Device: iPhone
 - OS: iOS 15
 - SDK Version : 3.8.4

### PR DESCRIPTION
**Pull request by ffittschen**
## Summary

By archiving different versions of Adyen to find the version that fixed the compilation with Xcode 13, I noticed that the project still includes the `armv7` architectures on the `v3` branch, whereas they are excluded on the `develop` branch (since 4.0.0). For that reason, this PR also excludes the `armv7` architectures for the project, so that it can still be archived using Xcode 13.

## Tested scenarios
Archiving the `Adyen` scheme with Xcode 13 succeeds after applying these changes.

Resolves #635.

### CODE REVIEW

**Review by RajaZahid — APPROVED** [review]

**Comment by RajaZahid** [comment]
Hi, anyone can merge this pull request? Need to generate builds but stuck due to this issue.

**Comment by descorp** [comment]
Hey @ffittschen @RajaZahid 

I believe there is a bit more [elegant solution](https://github.com/Adyen/adyen-ios/pull/640)
Kudo to @ffittschen for pointing out the!

**Comment by ffittschen** [comment]
Thanks for the fix @descorp. I just checked out the latest `v3` branch and can confirm that archiving with Xcode 13 works fine now 👍🏻

Would you be able to cut a new release for this bugfix?

And I'm closing this PR, as it was resolved by #640.

**Comment by descorp** [comment]
Hey @ffittschen 

We will roll out new 3.8.6. release in the next couple of week!

**Pull request closed without merging**
