### PR TITLE
add tintColor to FormSwitchItemStyle

### PR DESCRIPTION
**Pull request by zhantx**
add tintColor to FormSwitchItemStyle

### CODE REVIEW

**Comment by descorp** [comment]
Hi @zhantx 

Great thanks for your contribution!

This feature already developed and waiting to be released.
The next version will introduce a small framework for convenient tinting DropIn and individual components, including UISwitch, text and icons.

P.S. We are considering moving our public SDK development purely in GitHub.
It is going to make our work progress more transparent and your contributions even more important!

**Comment by zhantx** [comment]
Hey @descorp 
It's good to hear that, can you make sure android supports same customisation as well?

**Comment by descorp** [comment]
Hey @zhantx 

Android already supports it:

https://github.com/Adyen/adyen-android/blob/b0cb30c237c469c442b8b5f348fb6ded2df5105c/card-ui-core/src/main/res/values/styles.xml#L54

just need to override this style on your end.

**Comment by descorp** [comment]
Hi @zhantx 

We just released 3.6.0. 
`tintColor` is now available for all tintable component, uncluding `FormSwitchItemStyle`.

I am going to close this PR.
Thank you for your time and your contribution!

If you have any questions about `tintColor` feel free to ask them here or create a dedicated issue.

**Pull request closed without merging**
